apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: your-repo/python-app:latest
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi" # Maximum memory this container can use
            cpu: "500m" # Maximum CPU this container can use
          requests:
            memory: "256Mi" # Guaranteed minimum memory for this container
            cpu: "250m" # Guaranteed minimum CPU for this container
